const TONE_BY_STATUS: Record<string, string> = {
  ACTIVE: 'success',
  PUBLISHED: 'success',
  APPROVED: 'success',
  SUSPENDED: 'warning',
  DRAFT: 'neutral',
  PROVISIONING: 'info',
  REVIEW: 'info',
  INVITED: 'info',
  DEPRECATED: 'warning',
  DISABLED: 'danger',
  TERMINATED: 'danger',
  RETIRED: 'danger',
  ARCHIVED: 'neutral',
  REVOKED: 'danger',
  COMPLETED: 'success',
  SENT: 'success',
  DELIVERED: 'success',
  RUNNING: 'info',
  PROCESSING: 'info',
  WAITING: 'info',
  WAITING_APPROVAL: 'info',
  PENDING: 'info',
  QUEUED: 'info',
  IN_PROGRESS: 'info',
  FAILED: 'danger',
  REJECTED: 'danger',
  DISCARDED: 'danger',
  TIMEOUT: 'danger',
  CANCELLED: 'warning',
  RETURNED: 'warning',
  EXPIRED: 'warning',
  INACTIVE: 'neutral',
  ROTATED: 'neutral',
};

export function StatusBadge({ status }: { status: string }) {
  const tone = TONE_BY_STATUS[status] ?? 'neutral';
  return <span className={`badge badge-${tone}`}>{status}</span>;
}
